// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLK2v-94Lw1Jl1LvTzf4ra0CCW3llkSKE',
    appId: '1:7753173160:web:497cb174b4d08efd09da9d',
    messagingSenderId: '7753173160',
    projectId: 'coupleshareschedule',
    authDomain: 'coupleshareschedule.firebaseapp.com',
    storageBucket: 'coupleshareschedule.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaf-cIngHsRUGI65Nu1wL8dSct_SkgALs',
    appId: '1:7753173160:android:547b51a2daffb39509da9d',
    messagingSenderId: '7753173160',
    projectId: 'coupleshareschedule',
    storageBucket: 'coupleshareschedule.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH9BVhye9Up6-oO0jrkHMNPbmLAwBB6Pk',
    appId: '1:7753173160:ios:93d83c3fffd9718109da9d',
    messagingSenderId: '7753173160',
    projectId: 'coupleshareschedule',
    storageBucket: 'coupleshareschedule.appspot.com',
    iosClientId: '7753173160-idtf577vji9puhdiu1068id5l50i262a.apps.googleusercontent.com',
    iosBundleId: 'com.example.coupleShareSchedule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH9BVhye9Up6-oO0jrkHMNPbmLAwBB6Pk',
    appId: '1:7753173160:ios:93d83c3fffd9718109da9d',
    messagingSenderId: '7753173160',
    projectId: 'coupleshareschedule',
    storageBucket: 'coupleshareschedule.appspot.com',
    iosClientId: '7753173160-idtf577vji9puhdiu1068id5l50i262a.apps.googleusercontent.com',
    iosBundleId: 'com.example.coupleShareSchedule',
  );
}
